steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/papertrend-repo/papertrend-extractor:$SHORT_SHA
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/papertrend-repo/papertrend-extractor:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/papertrend-repo/papertrend-extractor:$SHORT_SHA

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/papertrend-repo/papertrend-extractor:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - papertrend-extractor
      - --image
      - us-central1-docker.pkg.dev/$PROJECT_ID/papertrend-repo/papertrend-extractor:$SHORT_SHA
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/papertrend-repo/papertrend-extractor:$SHORT_SHA
  - us-central1-docker.pkg.dev/$PROJECT_ID/papertrend-repo/papertrend-extractor:latest
