"""
EIL Research Trend Dashboard
=============================
Streamlit app that visualises outputs from the LLM-based extraction pipeline.

Expected data files (generated by the notebook):
  • Master_Trends_Archive.csv   – keyword-level rows
  • EIL_Track_OneHot_Final.csv  – multi-label track classification
  • EIL_Track_10years1.csv      – single-choice track classification

Launch:  streamlit run dashboard.py
"""

import os
import json
import textwrap
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
from collections import Counter

# ─── PAGE CONFIG ────────────────────────────────────────────────────
st.set_page_config(
    page_title="EIL Research Trend Dashboard",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─── CUSTOM CSS ─────────────────────────────────────────────────────
st.markdown("""
<style>
    /* Metric cards */
    div[data-testid="stMetric"] {
        background: linear-gradient(135deg, #667eea11, #764ba211);
        border: 1px solid #e0e0e0;
        border-radius: 12px;
        padding: 12px 16px;
    }
    /* Sidebar */
    section[data-testid="stSidebar"] { background: #fafbfc; }
    /* Header divider */
    .block-container { padding-top: 1rem; }
</style>
""", unsafe_allow_html=True)

# ─── DATA LOADING ──────────────────────────────────────────────────
DATA_DIR = os.path.dirname(os.path.abspath(__file__))

@st.cache_data
def load_trends():
    path = os.path.join(DATA_DIR, "Master_Trends_Archive.csv")
    if not os.path.exists(path):
        return None
    df = pd.read_csv(path)
    df["year"] = df["year"].astype(str)
    return df

@st.cache_data
def load_tracks_multi():
    path = os.path.join(DATA_DIR, "EIL_Track_OneHot_Final.csv")
    if not os.path.exists(path):
        return None
    df = pd.read_csv(path)
    df["year"] = df["year"].astype(str)
    return df

@st.cache_data
def load_tracks_single():
    path = os.path.join(DATA_DIR, "EIL_Track_10years1.csv")
    if not os.path.exists(path):
        return None
    df = pd.read_csv(path)
    df["year"] = df["year"].astype(str)
    return df

@st.cache_data
def load_json_archive():
    path = os.path.join(DATA_DIR, "Master_Trends_Archive.json")
    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

df_trends = load_trends()
df_multi = load_tracks_multi()
df_single = load_tracks_single()

# ─── HELPERS ────────────────────────────────────────────────────────
TRACK_COLS = ["EL", "ELI", "LAE", "Other"]
TRACK_COLORS = {"EL": "#636efa", "ELI": "#ef553b", "LAE": "#00cc96", "Other": "#ab63fa"}
TRACK_NAMES = {
    "EL": "English Linguistics",
    "ELI": "English Language Instruction",
    "LAE": "Language Assessment & Evaluation",
    "Other": "Other / General",
}

def safe_years(df):
    """Return sorted unique years from a dataframe."""
    if df is None:
        return []
    return sorted(df["year"].unique().tolist())


def build_track_long(df_track):
    """Melt track one-hot df into long format for easy plotting."""
    rows = []
    for _, r in df_track.iterrows():
        for t in TRACK_COLS:
            if r.get(t, 0) == 1:
                rows.append({"paper_id": r["paper_id"], "year": r["year"],
                             "title": r["title"], "track": t})
    return pd.DataFrame(rows)


def filter_by_sidebar(df, year_col="year"):
    """Apply the global sidebar filters (year range + track) to a df."""
    if df is None or df.empty:
        return df
    mask = df[year_col].isin(selected_years) if selected_years else pd.Series([True]*len(df))
    return df[mask]

# ─── SIDEBAR (GLOBAL FILTERS) ──────────────────────────────────────
st.sidebar.image("https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Chulalongkorn_University_Official_Logo.svg/150px-Chulalongkorn_University_Official_Logo.svg.png", width=80)
st.sidebar.title("🔬 EIL Dashboard")
st.sidebar.caption("English as an International Language — Chulalongkorn University")
st.sidebar.markdown("---")

# Determine available years across all data
all_years = sorted(set(safe_years(df_trends) + safe_years(df_multi) + safe_years(df_single)))

if all_years:
    selected_years = st.sidebar.multiselect(
        "📅 Filter by Year",
        options=all_years,
        default=all_years,
        help="Select one or more academic years",
    )
else:
    selected_years = []

selected_tracks = st.sidebar.multiselect(
    "🎯 Filter by Track",
    options=TRACK_COLS,
    default=TRACK_COLS,
    format_func=lambda x: f"{x} — {TRACK_NAMES[x]}",
)

st.sidebar.markdown("---")
st.sidebar.info(
    "Upload the CSV files generated by the EIL extraction pipeline "
    "into the same folder as this dashboard."
)

# ─── CHECK DATA AVAILABILITY ───────────────────────────────────────
data_available = any(x is not None for x in [df_trends, df_multi, df_single])

if not data_available:
    st.warning(
        "⚠️ No data files found. Please run the extraction pipeline first to generate:\n"
        "- `Master_Trends_Archive.csv`\n"
        "- `EIL_Track_OneHot_Final.csv`\n"
        "- `EIL_Track_10years1.csv`\n\n"
        "Place them in the same directory as `dashboard.py`."
    )
    st.stop()

# ═══════════════════════════════════════════════════════════════════
# TAB LAYOUT
# ═══════════════════════════════════════════════════════════════════
tab_overview, tab_trends, tab_tracks, tab_keywords, tab_explorer = st.tabs([
    "📋 Overview",
    "📈 Trend Analysis",
    "🎯 Track Analysis",
    "🔑 Keyword Explorer",
    "🔍 Paper Explorer",
])


# ═══════════════════════════════════════════════════════════════════
# TAB 1: OVERVIEW
# ═══════════════════════════════════════════════════════════════════
with tab_overview:
    st.header("Research Overview")

    # --- Metric cards ---
    col1, col2, col3, col4 = st.columns(4)

    if df_trends is not None:
        df_t = filter_by_sidebar(df_trends)
        n_papers = df_t["paper_id"].nunique()
        n_keywords = df_t["keyword"].nunique()
        n_topics = df_t["topic"].nunique()
        year_span = f"{df_t['year'].min()} – {df_t['year'].max()}" if len(df_t) else "—"
    else:
        n_papers = n_keywords = n_topics = 0
        year_span = "—"

    col1.metric("📄 Total Papers", n_papers)
    col2.metric("🏷️ Unique Topics", n_topics)
    col3.metric("🔑 Unique Keywords", n_keywords)
    col4.metric("📅 Year Span", year_span)

    st.markdown("---")

    # --- Papers per year ---
    if df_trends is not None and not df_t.empty:
        papers_per_year = df_t.groupby("year")["paper_id"].nunique().reset_index()
        papers_per_year.columns = ["Year", "Papers"]
        fig_ppy = px.bar(
            papers_per_year, x="Year", y="Papers",
            title="Papers Published per Year",
            color_discrete_sequence=["#636efa"],
            text="Papers",
        )
        fig_ppy.update_traces(textposition="outside")
        fig_ppy.update_layout(yaxis_title="Number of Papers", xaxis_title="Academic Year")
        st.plotly_chart(fig_ppy, use_container_width=True)

    # --- Track distribution (donut) ---
    if df_single is not None:
        df_s = filter_by_sidebar(df_single)
        if not df_s.empty:
            track_counts = {t: int(df_s[t].sum()) for t in TRACK_COLS if t in selected_tracks}
            if track_counts:
                c1, c2 = st.columns(2)
                with c1:
                    fig_donut = px.pie(
                        names=list(track_counts.keys()),
                        values=list(track_counts.values()),
                        title="Track Distribution (Single-Choice)",
                        color=list(track_counts.keys()),
                        color_discrete_map=TRACK_COLORS,
                        hole=0.45,
                    )
                    fig_donut.update_traces(textinfo="label+percent+value")
                    st.plotly_chart(fig_donut, use_container_width=True)

                with c2:
                    if df_multi is not None:
                        df_m = filter_by_sidebar(df_multi)
                        multi_counts = {t: int(df_m[t].sum()) for t in TRACK_COLS if t in selected_tracks}
                        fig_donut2 = px.pie(
                            names=list(multi_counts.keys()),
                            values=list(multi_counts.values()),
                            title="Track Distribution (Multi-Label)",
                            color=list(multi_counts.keys()),
                            color_discrete_map=TRACK_COLORS,
                            hole=0.45,
                        )
                        fig_donut2.update_traces(textinfo="label+percent+value")
                        st.plotly_chart(fig_donut2, use_container_width=True)


# ═══════════════════════════════════════════════════════════════════
# TAB 2: TREND ANALYSIS
# ═══════════════════════════════════════════════════════════════════
with tab_trends:
    st.header("Research Trend Analysis")

    if df_trends is None:
        st.info("Waiting for `Master_Trends_Archive.csv`...")
    else:
        df_t = filter_by_sidebar(df_trends)

        if df_t.empty:
            st.warning("No data for the selected filters.")
        else:
            # --- Topic frequency over time (area chart) ---
            st.subheader("Topic Trends Over Time")

            top_n_topics = st.slider("Show top N topics", 3, 25, 10, key="trend_topn")
            top_topics = df_t.groupby("topic")["paper_id"].nunique().nlargest(top_n_topics).index.tolist()
            trend_df = (
                df_t[df_t["topic"].isin(top_topics)]
                .groupby(["year", "topic"])["paper_id"]
                .nunique()
                .reset_index()
            )
            trend_df.columns = ["Year", "Topic", "Papers"]

            fig_area = px.area(
                trend_df, x="Year", y="Papers", color="Topic",
                title=f"Top {top_n_topics} Topics — Papers per Year",
                line_shape="spline",
            )
            fig_area.update_layout(legend=dict(orientation="h", y=-0.25))
            st.plotly_chart(fig_area, use_container_width=True)

            # --- Emerging vs Declining topics ---
            st.subheader("Emerging & Declining Topics")
            st.caption("Compares the first half vs second half of the selected year range.")

            sorted_yrs = sorted(df_t["year"].unique())
            if len(sorted_yrs) >= 2:
                mid = len(sorted_yrs) // 2
                early_years = sorted_yrs[:mid]
                late_years = sorted_yrs[mid:]

                early = df_t[df_t["year"].isin(early_years)].groupby("topic")["paper_id"].nunique()
                late = df_t[df_t["year"].isin(late_years)].groupby("topic")["paper_id"].nunique()
                shift = (late.reindex(early.index.union(late.index), fill_value=0) -
                         early.reindex(early.index.union(late.index), fill_value=0))

                emerging = shift.nlargest(8).reset_index()
                emerging.columns = ["Topic", "Change"]
                declining = shift.nsmallest(8).reset_index()
                declining.columns = ["Topic", "Change"]

                e_col, d_col = st.columns(2)
                with e_col:
                    fig_e = px.bar(
                        emerging, x="Change", y="Topic", orientation="h",
                        title=f"🔺 Emerging ({early_years[0]}–{late_years[-1]})",
                        color_discrete_sequence=["#00cc96"],
                    )
                    st.plotly_chart(fig_e, use_container_width=True)
                with d_col:
                    fig_d = px.bar(
                        declining, x="Change", y="Topic", orientation="h",
                        title=f"🔻 Declining ({early_years[0]}–{late_years[-1]})",
                        color_discrete_sequence=["#ef553b"],
                    )
                    st.plotly_chart(fig_d, use_container_width=True)
            else:
                st.info("Need data from ≥ 2 years to detect trends.")

            # --- Keyword frequency heatmap ---
            st.subheader("Keyword Frequency Heatmap")
            top_kw_n = st.slider("Show top N keywords", 5, 40, 15, key="kw_heatmap_n")
            top_kws = df_t.groupby("keyword")["keyword_frequency"].sum().nlargest(top_kw_n).index.tolist()
            heat_df = (
                df_t[df_t["keyword"].isin(top_kws)]
                .groupby(["year", "keyword"])["keyword_frequency"]
                .sum()
                .reset_index()
                .pivot(index="keyword", columns="year", values="keyword_frequency")
                .fillna(0)
            )
            fig_heat = px.imshow(
                heat_df, aspect="auto",
                color_continuous_scale="YlOrRd",
                title=f"Top {top_kw_n} Keywords × Year",
                labels=dict(color="Frequency"),
            )
            fig_heat.update_layout(height=max(400, top_kw_n * 28))
            st.plotly_chart(fig_heat, use_container_width=True)


# ═══════════════════════════════════════════════════════════════════
# TAB 3: TRACK ANALYSIS
# ═══════════════════════════════════════════════════════════════════
with tab_tracks:
    st.header("EIL Track Analysis")

    if df_single is None and df_multi is None:
        st.info("Waiting for track classification CSV files...")
    else:
        # --- Single-choice: stacked bar by year ---
        if df_single is not None:
            df_s = filter_by_sidebar(df_single)
            if not df_s.empty:
                st.subheader("Papers per Track per Year (Single-Choice)")
                track_year = df_s.groupby("year")[TRACK_COLS].sum().reset_index()
                track_year_long = track_year.melt(
                    id_vars="year", value_vars=[t for t in TRACK_COLS if t in selected_tracks],
                    var_name="Track", value_name="Papers",
                )
                fig_stack = px.bar(
                    track_year_long, x="year", y="Papers", color="Track",
                    barmode="stack",
                    color_discrete_map=TRACK_COLORS,
                    title="Track Composition Over Time",
                )
                fig_stack.update_layout(xaxis_title="Year", legend=dict(orientation="h", y=-0.2))
                st.plotly_chart(fig_stack, use_container_width=True)

        # --- Multi-label overlap matrix ---
        if df_multi is not None:
            df_m = filter_by_sidebar(df_multi)
            if not df_m.empty:
                st.subheader("Track Co-occurrence (Multi-Label Overlap)")
                st.caption("How often two tracks appear together on the same paper.")

                overlap = pd.DataFrame(index=TRACK_COLS, columns=TRACK_COLS, dtype=float)
                for t1 in TRACK_COLS:
                    for t2 in TRACK_COLS:
                        overlap.loc[t1, t2] = ((df_m[t1] == 1) & (df_m[t2] == 1)).sum()

                fig_overlap = px.imshow(
                    overlap.astype(float), text_auto=True,
                    color_continuous_scale="Blues",
                    title="Track Co-occurrence Matrix",
                )
                st.plotly_chart(fig_overlap, use_container_width=True)

        # --- Top topics per track ---
        if df_trends is not None and df_single is not None:
            st.subheader("Top Topics per Track")
            df_t = filter_by_sidebar(df_trends)
            df_s = filter_by_sidebar(df_single)

            # Merge trends with single-choice tracks
            merged = df_t.merge(df_s[["paper_id", *TRACK_COLS]], on="paper_id", how="left")

            cols = st.columns(len(selected_tracks))
            for i, track in enumerate(selected_tracks):
                with cols[i]:
                    st.markdown(f"**{track}** — {TRACK_NAMES[track]}")
                    track_papers = merged[merged.get(track, 0) == 1]
                    if not track_papers.empty:
                        top = (
                            track_papers.groupby("topic")["paper_id"]
                            .nunique()
                            .nlargest(8)
                            .reset_index()
                        )
                        top.columns = ["Topic", "Papers"]
                        fig_t = px.bar(
                            top, x="Papers", y="Topic", orientation="h",
                            color_discrete_sequence=[TRACK_COLORS[track]],
                        )
                        fig_t.update_layout(
                            height=300, margin=dict(l=0, r=0, t=10, b=0),
                            showlegend=False,
                        )
                        st.plotly_chart(fig_t, use_container_width=True)
                    else:
                        st.caption("No data")


# ═══════════════════════════════════════════════════════════════════
# TAB 4: KEYWORD EXPLORER
# ═══════════════════════════════════════════════════════════════════
with tab_keywords:
    st.header("Keyword Explorer")

    if df_trends is None:
        st.info("Waiting for `Master_Trends_Archive.csv`...")
    else:
        df_t = filter_by_sidebar(df_trends)

        if df_t.empty:
            st.warning("No data for the selected filters.")
        else:
            # --- Search box ---
            kw_search = st.text_input("🔍 Search keywords", "", placeholder="e.g. translanguaging, assessment...")

            kw_agg = (
                df_t.groupby("keyword")
                .agg(
                    total_freq=("keyword_frequency", "sum"),
                    papers=("paper_id", "nunique"),
                    years=("year", lambda x: ", ".join(sorted(x.unique()))),
                    topics=("topic", lambda x: ", ".join(x.unique())),
                )
                .reset_index()
                .sort_values("total_freq", ascending=False)
            )

            if kw_search:
                kw_agg = kw_agg[kw_agg["keyword"].str.contains(kw_search, case=False, na=False)]

            # --- Word cloud style: treemap ---
            st.subheader("Keyword Treemap")
            top_tree_n = st.slider("Show top N", 10, 60, 30, key="treemap_n")
            tree_data = kw_agg.head(top_tree_n)
            if not tree_data.empty:
                fig_tree = px.treemap(
                    tree_data,
                    path=["keyword"],
                    values="total_freq",
                    color="total_freq",
                    color_continuous_scale="Viridis",
                    title="Keyword Frequency Treemap",
                )
                fig_tree.update_layout(height=500)
                st.plotly_chart(fig_tree, use_container_width=True)

            # --- Sortable table ---
            st.subheader("Keyword Table")
            st.dataframe(
                kw_agg.rename(columns={
                    "keyword": "Keyword",
                    "total_freq": "Total Frequency",
                    "papers": "Papers",
                    "years": "Years Active",
                    "topics": "Associated Topics",
                }),
                use_container_width=True,
                height=450,
            )

            # --- Keyword timeline ---
            st.subheader("Keyword Timeline")
            sel_kws = st.multiselect(
                "Select keywords to compare",
                options=kw_agg["keyword"].tolist(),
                default=kw_agg["keyword"].head(5).tolist(),
                key="kw_timeline_select",
            )
            if sel_kws:
                timeline = (
                    df_t[df_t["keyword"].isin(sel_kws)]
                    .groupby(["year", "keyword"])["keyword_frequency"]
                    .sum()
                    .reset_index()
                )
                fig_kw_line = px.line(
                    timeline, x="year", y="keyword_frequency",
                    color="keyword", markers=True,
                    title="Selected Keywords Over Time",
                )
                fig_kw_line.update_layout(xaxis_title="Year", yaxis_title="Frequency")
                st.plotly_chart(fig_kw_line, use_container_width=True)


# ═══════════════════════════════════════════════════════════════════
# TAB 5: PAPER EXPLORER
# ═══════════════════════════════════════════════════════════════════
with tab_explorer:
    st.header("Paper Explorer")

    if df_trends is None:
        st.info("Waiting for `Master_Trends_Archive.csv`...")
    else:
        df_t = filter_by_sidebar(df_trends)

        if df_t.empty:
            st.warning("No data for the selected filters.")
        else:
            # --- Paper search ---
            paper_search = st.text_input("🔍 Search by title", "", placeholder="e.g. peer feedback, EFL...")

            papers = df_t.groupby(["paper_id", "year", "title"]).agg(
                topics=("topic", lambda x: ", ".join(x.unique())),
                keywords=("keyword", lambda x: ", ".join(x.unique())),
                kw_count=("keyword", "nunique"),
            ).reset_index().sort_values("year", ascending=False)

            # Merge track info if available
            if df_single is not None:
                df_s_filt = filter_by_sidebar(df_single)
                track_labels = []
                for _, row in df_s_filt.iterrows():
                    tracks = [t for t in TRACK_COLS if row.get(t, 0) == 1]
                    track_labels.append({"paper_id": row["paper_id"], "track": ", ".join(tracks) if tracks else "—"})
                if track_labels:
                    tl_df = pd.DataFrame(track_labels)
                    papers = papers.merge(tl_df, on="paper_id", how="left")

            if paper_search:
                papers = papers[papers["title"].str.contains(paper_search, case=False, na=False)]

            st.dataframe(
                papers.rename(columns={
                    "paper_id": "ID",
                    "year": "Year",
                    "title": "Title",
                    "topics": "Topics",
                    "keywords": "Keywords",
                    "kw_count": "# Keywords",
                    "track": "Track",
                }),
                use_container_width=True,
                height=500,
            )

            # --- Paper detail expander ---
            st.subheader("Paper Detail View")
            paper_ids = papers["paper_id"].unique().tolist()
            if paper_ids:
                selected_pid = st.selectbox("Select a paper ID", paper_ids, key="paper_detail_select")
                paper_rows = df_t[df_t["paper_id"] == selected_pid]
                if not paper_rows.empty:
                    st.markdown(f"### {paper_rows.iloc[0]['title']}")
                    st.markdown(f"**Year:** {paper_rows.iloc[0]['year']}")

                    # Track badge
                    if df_single is not None:
                        track_row = df_single[df_single["paper_id"] == selected_pid]
                        if not track_row.empty:
                            tracks = [t for t in TRACK_COLS if track_row.iloc[0].get(t, 0) == 1]
                            if tracks:
                                st.markdown("**Track(s):** " + " · ".join(f"`{t}`" for t in tracks))

                    # Keywords + evidence table
                    detail = paper_rows[["keyword", "keyword_frequency", "topic", "evidence"]].copy()
                    detail.columns = ["Keyword", "Frequency", "Topic", "Evidence (Verbatim)"]
                    st.dataframe(detail, use_container_width=True)


# ═══════════════════════════════════════════════════════════════════
# FOOTER
# ═══════════════════════════════════════════════════════════════════
st.markdown("---")
st.caption(
    "EIL Research Trend Dashboard · "
    "English as an International Language Program · "
    "Chulalongkorn University · "
    "Powered by LangChain + LangGraph + Streamlit"
)
