/**
 * Writes src/components/ui/icon-glyphs.ts: the drawing of each Phosphor icon
 * that src/components/ui/Icons.tsx imports, in the three weights the app uses
 * (regular, bold and fill).
 *
 * Each Phosphor icon carries all six of its weights, so every icon on a page
 * shipped thin, light and duotone drawings nobody saw - about half of the
 * icon code on the landing page (docs/32, 3.3). Run after changing the icons
 * Icons.tsx imports: `node scripts/generate-icons.mjs`. A test fails when the
 * two disagree.
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";

// Phosphor's per-icon drawings, by path: the package's exports map sends a
// subpath import to the whole bundle. Copied as .mjs so Node reads them as
// modules; "react" resolves from this project.
const DEFINITIONS = new URL("../node_modules/@phosphor-icons/react/dist/defs/", import.meta.url);
const WORK = new URL("../node_modules/.cache/generate-icons/", import.meta.url);
mkdirSync(WORK, { recursive: true });
const WEIGHTS = ["regular", "bold", "fill"];
const icons = readFileSync(new URL("../src/components/ui/Icons.tsx", import.meta.url), "utf8");
const block = icons.match(/import \{([^}]*)\} from "\.\/icon-glyphs";/)?.[1];
if (!block) throw new Error('Icons.tsx has no import from "./icon-glyphs".');
const names = block
  .split(",")
  .map((part) => part.trim().split(/\s+as\s+/)[0].trim())
  .filter(Boolean)
  .map((name) => name.replace(/Glyph$/, ""));

function nodesOf(element) {
  const children = element?.props?.children;
  const list = Array.isArray(children) ? children : children ? [children] : [];
  return list.filter(Boolean).map((child) => {
    const { children: nested, ...props } = child.props ?? {};
    if (nested) throw new Error(`Nested drawing in a Phosphor icon is not supported (${child.type}).`);
    return [child.type, props];
  });
}

const lines = [
  "// Generated by scripts/generate-icons.mjs from @phosphor-icons/react - do not edit by hand.",
  "// Each icon's drawing in the weights the app uses; see that script for why.",
  "",
  "export type GlyphNode = readonly [tag: string, props: Readonly<Record<string, string | number>>];",
  "export type GlyphWeights = { readonly regular: readonly GlyphNode[]; readonly bold: readonly GlyphNode[]; readonly fill: readonly GlyphNode[] };",
  "",
];
for (const name of [...new Set(names)].sort()) {
  const copy = new URL(`${name}.mjs`, WORK);
  copyFileSync(new URL(`${name}.es.js`, DEFINITIONS), copy);
  const definitions = await import(copy.href);
  const weights = definitions.default;
  const drawn = Object.fromEntries(WEIGHTS.map((weight) => [weight, nodesOf(weights.get(weight))]));
  lines.push(`export const ${name}Glyph: GlyphWeights = ${JSON.stringify(drawn)};`);
}
writeFileSync(new URL("../src/components/ui/icon-glyphs.ts", import.meta.url), `${lines.join("\n")}\n`);
console.log(`icon-glyphs.ts: ${new Set(names).size} icons`);
