import type { DocsCategoryBase } from "./types";

export const helpCategory: DocsCategoryBase = {
  id: "help",
  label: "Help",
  description: "What a message means and what to do about it, and the words Papertrend uses.",
  pages: [
    {
      slug: "troubleshooting",
      title: "Troubleshooting",
      description:
        "The messages you may meet when signing in, uploading, analyzing, charting or chatting: what each means and what to do next.",
      tags: ["troubleshooting", "errors", "failed", "stuck", "help", "messages"],
      popular: true,
      related: ["uploading-papers", "analysis-pipeline", "chat"],
      sections: [
        {
          id: "first-steps",
          title: "Before anything else",
          body: ["Most problems clear with one of these, in this order:"],
          checklist: [
            "Press **Refresh** on the dashboard, or reload the page. New results do not appear on their own.",
            "Check which repository is open: its name sits at the top left. The Dashboard and Chat use that one.",
            "Open the Library and look at the paper's status. A failed paper says why.",
            "Wait a minute and try again. Most model and network errors are brief.",
          ],
        },
        {
          id: "signing-in",
          title: "Signing in",
          body: [],
          table: {
            columns: ["You see", "What to do"],
            rows: [
              ["Confirm your email address", "Open the confirmation link we emailed you (check spam too), then choose **I’ve confirmed it**. **Send the link again** if it has not arrived."],
              ["A Papertrend account already uses this email address.", "You signed in with Facebook, and an account already has that email. Sign in with Google, or with your email and password, instead."],
              ["Too many attempts for now.", "Sign-in attempts are limited after several failures. Wait a few minutes, or reset your password to sign in straight away."],
              ["Sign-in timed out while contacting the authentication service.", "The Google or Facebook window did not finish in time. Allow pop-ups for the site and try again."],
              ["Wrong password, pop-up closed or blocked, too many requests", "Check the password or use **Reset password**, allow pop-ups, or wait a few minutes if there were many attempts."],
              ["Enter your email first, then request a reset link.", "Type your email address, then choose **Reset password**."],
              ["Papertrend can't be reached right now. Trying again…", "Your connection or the server had a brief problem. Papertrend keeps trying on its own; if it gives up, check your connection and reload the page. You stay signed in."],
              ["Enter your invite code", "Papertrend is invite-only for now. Enter the code you were given; it works once, for your account."],
              ["This is Papertrend's test deployment", "You opened the test site, which only the project owner can use. Use the main Papertrend site instead."],
              ["Your sign-in has ended. Please sign in again.", "Your session ended. Sign in again; you come back to the page you were on."],
            ],
          },
        },
        {
          id: "uploading",
          title: "Uploading",
          body: [],
          table: {
            columns: ["You see", "What to do"],
            rows: [
              ["N files were skipped. Only PDFs of 10 MB or less can be added.", "Convert the file to PDF, or compress or split it below 10 MB."],
              ["Only the first 50 PDFs were kept.", "Add the rest in a second upload."],
              ["This account can store up to 50 papers.", "The account is full, and papers in Trash count too. Delete papers permanently from Trash to make room."],
              ["Already analyzed in this account: <names>.", "The same PDF is already in one of your repositories, or in Trash. Remove it from this upload, or restore it from Trash. A PDF can belong to one repository."],
              ["The same PDF was selected more than once.", "Remove the second copy from the selection."],
              ["The upload could not be prepared (status <code>).", "Try again in a moment; if it repeats, note the status code for the operators."],
              ["...(after 3 attempts), or N files could not be uploaded.", "The connection dropped three times. The files are marked failed in the Library; add them again when the connection is steady."],
              ["The upload finished but analysis could not be started.", "Open the progress tray and choose **Start now**."],
              ["Uploaded, but analysis has not started", "Choose **Start now** in the tray, or **Start processing now** on Home."],
              ["Waiting for another analysis to finish", "Papers are analyzed one after another. Nothing to do; yours is in line."],
            ],
          },
        },
        {
          id: "analysis",
          title: "Analysis stuck or failed",
          body: [
            "A paper normally takes one to three minutes. Long theses and scanned PDFs take longer, and a single step can run for several minutes without an update.",
          ],
          table: {
            columns: ["You see", "What to do"],
            rows: [
              ["Still working. This step has been running for about...", "The paper is still being read. Wait."],
              ["Nothing has moved for about N minutes.", "Choose **Retry processing**."],
              ["Stopped updating, or Needs attention on Home", "Open the Library; choose **Try again** on the paper."],
              ["Recovered stalled analysis run", "The worker put the paper back in line by itself. Wait."],
              ["The analysis worker stopped updating this run too many times.", "Choose **Try again**. If it fails again, the PDF itself may be the problem: re-save it and upload it again."],
              ["Canceled by user", "Someone chose **Cancel analysis**. **Try again** restarts it."],
              ["Upload did not produce a storage path", "The upload was interrupted, often by closing the tab. Add the file again."],
              ["Critical extraction failure", "The PDF could not be opened. Re-save it (for example with Print to PDF) and upload it again."],
              ["Extraction produced no usable text", "The PDF has no text and the scan could not be read. Upload a text-based PDF or a clearer scan."],
              ["The file took too long to download, or a network or storage error", "**Try again**; this usually works."],
              ["Analyzing again did not finish; the earlier results are shown.", "The earlier results are safe. Try **Analyze again** later."],
            ],
          },
          callout: {
            tone: "info",
            title: "Where to find the reason",
            body: "A failed paper's reason shows under its name in the Library and in the progress tray, together with the step it stopped at.",
          },
        },
        {
          id: "results",
          title: "Results look wrong on a paper",
          body: [],
          table: {
            columns: ["Symptom", "What to do"],
            rows: [
              ["The year is Unknown or wrong", "The year was not printed clearly enough to trust. Choose **Correct title or year** in the paper explorer; a correction survives any later re-analysis."],
              ["The title is a running header or cut short", "**Correct title or year** (3 to 500 characters)."],
              ["Other / Unclassified", "The evidence did not fit a category clearly, or classification failed. Check the categories' descriptions in Settings, then reclassify or analyze the paper again."],
              ["Needs reclassification", "The paper was sorted under an earlier profile. **Settings**, **Analysis & classification**, **Reclassify existing papers**."],
              ["Classification not enabled", "The repository uses General Research. Choose EIL Tracks or your own categories in Settings to sort papers."],
              ["Analysis notes about OCR, translation or page limits", "A step read only part of the paper. Check key facts against the PDF."],
              ["Possible copy of \"<title>\"", "Another paper in the repository has almost the same text. Keep one and move the other to Trash."],
              ["Preview URL was not available", "The preview link expired (links last an hour). Choose **Refresh preview**."],
            ],
          },
        },
        {
          id: "dashboard",
          title: "Dashboard",
          body: [],
          table: {
            columns: ["You see", "What to do"],
            rows: [
              ["A newly analyzed paper is missing", "Press **Refresh**."],
              ["Dashboard data could not be loaded for this repository.", "Reload the page, or press **Refresh**."],
              ["Grouping N new topics into themes", "Wait; the charts update within about a minute."],
              ["...shown under their own labels, because grouping could not run", "Nothing to do; grouping is tried again later and the charts still work."],
              ["No papers match the current filters.", "Choose **Show all** under the year or category chips, and clear the search box."],
              ["Nothing to show: this repository does not sort papers into categories.", "Choose categories in Settings if you want this view."],
              ["N papers look like a second copy of another paper here.", "**Show which**, open each in the Library and move one copy to Trash."],
              ["Map out of date", "Choose **Update map**."],
              ["Map generation failed. Your previous map is still available.", "Try **Update map** again later."],
              ["Nothing strong enough to show yet (Adaptive)", "No pattern in the selection has 3 papers behind it. Widen the years or categories, or clear the search."],
              ["Daily AI usage limit reached (Adaptive)", "The day's 100 write-ups and questions are used. The computed insights still show; try the AI again after 07:00 Thailand time."],
            ],
          },
        },
        {
          id: "chat",
          title: "Chat",
          body: [],
          table: {
            columns: ["You see", "What to do"],
            rows: [
              ["No completed, analyzed papers were found in <scope>.", "Nothing in scope has finished analysis. Change the scope with **+**, **Repository scope**, or wait for your papers."],
              ["...no topic rows are available in <scope> yet.", "Those papers' topic step failed. Analyze them again."],
              ["Daily chat token limit reached", "The day's chat allowance is used; it resets at 07:00 Thailand time."],
              ["Daily AI usage limit reached.", "The day's 10 deep research runs, or 40 web searches, are used."],
              ["This answer took longer than the public gateway allows.", "Reopen the conversation in a minute: the answer may have arrived. Then ask again if needed."],
              ["The repository analysis could not be completed.", "A background answer failed. Send the question again."],
              ["I could not access the selected Papertrend knowledge scope", "Try again. If it repeats, send the operators the request ID shown."],
              ["I could not finish this answer.", "Ask again."],
              ["This chat request exceeded its safe context limit.", "Refresh the page; shorten the message or attach fewer papers."],
              ["Web search was on but no Web context section appeared", "The search found nothing it could cite, today's web search limit was reached, the step failed, or you were in Chart mode. The note under the answer says which."],
              ["The chat service returned an unreadable response.", "Try again; if it keeps happening, reload the page."],
            ],
          },
        },
        {
          id: "library",
          title: "Library and repositories",
          body: [],
          table: {
            columns: ["You see", "What to do"],
            rows: [
              ["Repositories could not be loaded", "Choose **Retry**. Your data has not been removed."],
              ["You are browsing <A>. Dashboard and Chat still use <B>.", "Choose **Switch to this repository** if the Dashboard and Chat should follow."],
              ["Open a repository before adding papers.", "Pick a repository on the Repositories page first."],
              ["A paper disappeared", "Look in **Trash** in the Library, and restore it."],
            ],
          },
        },
        {
          id: "still-stuck",
          title: "Still stuck",
          body: [
            "Note what you did, the exact message, the paper's name and the time, and send them to the operators. A request ID in a chat message identifies the request exactly. Never send your password.",
          ],
        },
      ],
    },
    {
      slug: "glossary",
      title: "Glossary",
      description: "The words Papertrend uses, as they appear on screen, and what each one means.",
      tags: ["glossary", "terms", "definitions", "vocabulary"],
      related: ["getting-started", "analysis-pipeline", "dashboard"],
      sections: [
        {
          id: "places",
          title: "Places",
          body: [],
          definitions: [
            { term: "Repository", detail: "A private collection of papers with its own analysis profile, Home, Dashboard and Chat. A repository cannot be deleted yet." },
            { term: "Repositories", detail: "The page listing your repositories, where you open, create and rename them." },
            { term: "Home", detail: "The open repository's front page: counts, a box to ask about the papers, the top topics and keywords, recent papers and analysis progress." },
            { term: "Library", detail: "Every paper in every repository you own, with each paper's status, Trash, renaming, favorites and analyzing again." },
            { term: "Open repository", detail: "The repository the Dashboard and Chat use. It is remembered in this browser. Browsing another repository in the Library does not change it." },
            { term: "Paper explorer", detail: "The window showing one paper's analysis, with the tabs Overview, Keywords, Evidence, Topics and Preview." },
            { term: "Progress tray", detail: "The small pill in the corner and the panel it opens, following each paper through the ten steps of analysis." },
            { term: "Trash", detail: "Where papers go when moved out of a repository. They can be restored; they leave every chart while there." },
          ],
        },
        {
          id: "analysis",
          title: "Analysis",
          body: [],
          definitions: [
            { term: "Analysis", detail: "The automatic reading of a paper: its text (scans included), sections, title and year, keywords, topics, category, research type and facets." },
            { term: "Queued, Analyzing, Ready, Failed", detail: "Waiting in line; being read; finished and usable in the Dashboard and Chat; stopped, with the reason shown." },
            { term: "The ten steps", detail: "Upload, Queued, Prepare, Read text, Sections, Metadata, Keywords, Classify, Save, Done." },
            { term: "Keyword", detail: "A concept found in the paper's own sections, never its reference list, with a sentence from the paper as evidence and a count of how often it appears." },
            { term: "The paper's own keywords", detail: "The keyword list printed in the paper by its authors, when it has one." },
            { term: "Topic", detail: "A group of one paper's related keywords with a short label, named for that paper. Subject topics and method topics are kept apart." },
            { term: "Method topic", detail: "A topic about how a study was done, such as its design or instruments. Shown under How these studies were done." },
            { term: "Facet", detail: "Short labels for what a paper sets out to do (such as investigate or compare) and what kind of contribution it makes, with evidence." },
            { term: "Research type", detail: "The broad kind of study, such as empirical or review, with an optional second type." },
            { term: "Evidence", detail: "The sentence from the paper supporting a keyword, facet, year or category." },
            { term: "Year source", detail: "Where the publication year was read, such as the journal issue line, with the line quoted." },
            { term: "Analysis notes", detail: "Notes left when a step read only part of a paper or used a simpler method, so results may be partial." },
            { term: "Possible copy", detail: "A paper whose text closely matches another paper in the same repository. Nothing is removed; you decide which to keep." },
            { term: "Analyze again", detail: "Runs the whole analysis again on the stored PDF with today's pipeline and the repository's profile. Your corrections are kept." },
          ],
        },
        {
          id: "categories",
          title: "Profiles and categories",
          body: [],
          definitions: [
            { term: "Analysis profile", detail: "A repository's setting for sorting papers into categories: General Research, EIL Tracks or Custom Taxonomy." },
            { term: "General Research", detail: "No categories. Everything else is still analyzed. The default for a new repository." },
            { term: "EIL Tracks", detail: "Three fixed categories for English as an International Language research: English Linguistics, English Language Instruction, and Language Assessment and Evaluation." },
            { term: "Custom Taxonomy", detail: "Your own 2 to 12 categories, each with a name and a description of what belongs in it." },
            { term: "Category", detail: "The class a paper is sorted into, one primary and up to two secondary, with the reason. Older charts and the report still call it a track." },
            { term: "Other / Unclassified", detail: "Added automatically for papers whose evidence is weak, mixed or outside the categories." },
            { term: "Reclassify", detail: "Sorts papers already analyzed under the saved profile again, from their stored text, without analyzing them again." },
          ],
        },
        {
          id: "dashboard",
          title: "Dashboard",
          body: [],
          definitions: [
            { term: "Theme", detail: "Topics from different papers that share a research focus, grouped by an AI model. Charts count papers per theme." },
            { term: "Drilldown", detail: "The window listing the papers behind a bar, slice or theme you click." },
            { term: "Semantic map", detail: "A picture where each dot is a paper, placed so that papers with similar content sit close together." },
            { term: "Neighborhood", detail: "A cluster of related papers on the semantic map, labeled with their most frequent terms." },
            { term: "Adaptive", detail: "The dashboard tab of computed insights: patterns in the selected papers, each resting on at least 3 papers, that no other tab shows. AI can word them or answer a question, but every number is computed." },
            { term: "Unknown year", detail: "Papers whose publication year could not be read. They are left out of charts over time and counted in a note." },
          ],
        },
        {
          id: "chat",
          title: "Chat",
          body: [],
          definitions: [
            { term: "Scope", detail: "Which papers a message may use: the open repository (the default), another repository, all repositories, or attached papers." },
            { term: "Attach papers", detail: "Picks specific papers, from any of your repositories, so a message uses only them." },
            { term: "Citation", detail: "A small number after a claim in an answer. Hover it to see the paper; the source cards below open it." },
            { term: "Coverage line", detail: "The line under an answer saying how many of the papers in scope it drew on." },
            { term: "Chart mode", detail: "Answers with a chart worked out from your question and computed from the repository's themes, methods, categories and years." },
            { term: "Web search", detail: "Adds current web sources to an answer, under Web context; every point cites the page it came from." },
            { term: "Deep research", detail: "A planned, budgeted investigation across your papers that writes a report with a numbered list of sources." },
            { term: "Background answer", detail: "A long answer that runs on the server and appears in the conversation when ready." },
          ],
        },
        {
          id: "account",
          title: "Account",
          body: [],
          definitions: [
            { term: "Member, Admin", detail: "Account roles. Admins are exempt from the 50-paper limit and the daily AI limits." },
            { term: "Daily limits", detail: "1,000,000 chat tokens, 40 web searches, 10 deep research runs and 100 Adaptive write-ups and questions a day, reset at 00:00 UTC (07:00 in Thailand)." },
            { term: "Favorite", detail: "A star on a paper in the Library." },
          ],
        },
      ],
    },
  ],
};
